# Generated by Django 2.2.2 on 2019-07-01 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('0', 'off'), ('1', 'on')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('timeToOpen', models.TimeField(blank=True)),
                ('timeToClose', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('timeToSend', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 1, 10, 56, 14, 61786), null=True)),
                ('timeToOrder', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 1, 10, 56, 14, 61786), null=True)),
                ('totalPriceOrder', models.PositiveIntegerField()),
                ('payments', models.CharField(choices=[('online', 'โอน'), ('clash', 'เงินสด'), ('online + clash', 'โอน + เงินสด')], max_length=50)),
                ('callService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.CallService')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateRider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeOrder', models.BooleanField(default=False)),
                ('timeTakeOrder', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 1, 10, 56, 14, 61786), null=True)),
                ('takeFood', models.BooleanField(default=False)),
                ('timeTakeFood', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 1, 10, 56, 14, 61786), null=True)),
                ('finishOrder', models.BooleanField(default=False)),
                ('timeFinishOrder', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 1, 10, 56, 14, 61786), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Order')),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Rider')),
                ('staterider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.StateRider')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('typefoods', models.CharField(choices=[('food', 'อาหาร'), ('drink', 'เครื่องดื่ม'), ('snack', 'ของทานเล่น'), ('noodle', 'ก๋วยเตี๋ยว')], max_length=10)),
                ('markets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priceBase', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('totalPriceMenu', models.PositiveIntegerField()),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Market')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Order')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Menu')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Option')),
            ],
        ),
    ]
