# Generated by Django 2.2.2 on 2019-07-02 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190702_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='exFood',
            field=models.CharField(choices=[('normal', 'ธรรมดา'), ('extra', 'พิเศษ')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='priceBaseEX',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 11, 54, 47, 501677), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToSend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 11, 54, 47, 501677), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeFinishOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 11, 54, 47, 500680), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeFood',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 11, 54, 47, 500680), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 11, 54, 47, 500680), null=True),
        ),
    ]
