# Generated by Django 2.2.2 on 2019-07-02 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20190702_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='foods',
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 13, 52, 40, 671130), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToSend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 13, 52, 40, 671130), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeFinishOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 13, 52, 40, 671130), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeFood',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 13, 52, 40, 671130), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 13, 52, 40, 671130), null=True),
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exFood', models.CharField(choices=[('normal', 'ธรรมดา'), ('extra', 'พิเศษ')], max_length=20)),
                ('priceBase', models.PositiveIntegerField()),
                ('markets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Market')),
            ],
        ),
        migrations.CreateModel(
            name='OnMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Drink')),
                ('foods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Food')),
                ('snack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Snack')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='onMenu',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.OnMenu'),
            preserve_default=False,
        ),
    ]
