# Generated by Django 2.2.2 on 2019-07-02 08:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20190702_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='onMenu',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.OnMenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 15, 1, 26, 177526), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToSend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 15, 1, 26, 177526), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeFinishOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 15, 1, 26, 177526), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeFood',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 15, 1, 26, 177526), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 2, 15, 1, 26, 177526), null=True),
        ),
    ]
