# Generated by Django 2.2.2 on 2019-07-22 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20190702_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onmenu',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Drink'),
        ),
        migrations.AlterField(
            model_name='onmenu',
            name='foods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Food'),
        ),
        migrations.AlterField(
            model_name='onmenu',
            name='snack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Snack'),
        ),
        migrations.AlterField(
            model_name='option',
            name='typefoods',
            field=models.CharField(choices=[('food', 'อาหาร'), ('drink', 'เครื่องดื่ม'), ('snack', 'ของทานเล่น'), ('bakery', 'ของหวาน')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 22, 21, 55, 7, 353342), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToSend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 22, 21, 55, 7, 353342), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeFinishOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 22, 21, 55, 7, 349218), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeFood',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 22, 21, 55, 7, 349218), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 22, 21, 55, 7, 349218), null=True),
        ),
    ]
