# Generated by Django 2.2.2 on 2019-08-11 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20190809_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='typefood',
            field=models.CharField(choices=[('food', 'อาหาร'), ('drink', 'เครื่องดื่ม'), ('snack', 'ของทานเล่น'), ('bakery', 'ของหวาน'), ('fruit', 'ผลไม้')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='typefood',
            field=models.CharField(choices=[('food', 'อาหาร'), ('drink', 'เครื่องดื่ม'), ('snack', 'ของทานเล่น'), ('bakery', 'ของหวาน'), ('fruit', 'ผลไม้')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snack',
            name='typefood',
            field=models.CharField(choices=[('food', 'อาหาร'), ('drink', 'เครื่องดื่ม'), ('snack', 'ของทานเล่น'), ('bakery', 'ของหวาน'), ('fruit', 'ผลไม้')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='typefoods',
            field=models.CharField(choices=[('food', 'อาหาร'), ('drink', 'เครื่องดื่ม'), ('snack', 'ของทานเล่น'), ('bakery', 'ของหวาน'), ('fruit', 'ผลไม้')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 11, 15, 52, 20, 734921), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeToSend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 11, 15, 52, 20, 734921), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeFinishOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 11, 15, 52, 20, 733923), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeFood',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 11, 15, 52, 20, 733923), null=True),
        ),
        migrations.AlterField(
            model_name='staterider',
            name='timeTakeOrder',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 11, 15, 52, 20, 733923), null=True),
        ),
    ]
